package main

import (
	"fmt"
	"path/filepath"

	"github.com/josephbudd/cwt/domain/data/filepaths"
	"github.com/josephbudd/cwt/domain/store"
	"github.com/josephbudd/cwt/domain/store/storing"
)

/*
	DO NOT EDIT THIS FILE.

	USE THE TOOL kickstore TO ADD OR REMOVE STORES.

	kickstore will edit this file for you.

*/

// buildStores makes and opens the data stores.
// It makes each local bolt data store API.
// It makes each remote service API.
// All of the stores and APIs can be opened with stores.Open()
// All of the stores and APIs can be close with stores.Close()
func buildStores() (stores *store.Stores, err error) {

	defer func() {
		if err != nil {
			err = fmt.Errorf("buildStores(): %w", err)
		}
	}()

	var path string
	if path, err = filepaths.BuildUserSubFoldersPath("boltdb"); err != nil {
		err = fmt.Errorf("filepaths.BuildUserSubFoldersPath(\"boltdb\"): %w", err)
		return
	}
	path = filepath.Join(path, "stores.nosql")
	stores = &store.Stores{
		// Local bolt stores.
		KeyCode: storing.NewKeyCodeLocalBoltStore(path, filepaths.GetFmode()),
		WPM    : storing.NewWPMLocalBoltStore(path, filepaths.GetFmode()),
	}
	return
}
