// +build js, wasm

package keynotreadypanel

import (
	"fmt"
	"syscall/js"

	"github.com/josephbudd/cwt/rendererprocess/api/markup"
	"github.com/josephbudd/cwt/rendererprocess/framework/viewtools"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// panelGroup is a group of 2 panels.
// It also has show panel funcs for each panel in this panel group.
type panelGroup struct {
	keyNotReadyPanel js.Value
	keyReadyPanel js.Value
}

func (group *panelGroup) defineMembers() (err error) {

	defer func() {
		if err != nil {
			err = fmt.Errorf("(group *panelGroup) defineMembers(): %w", err)
		}
	}()

    var panel *markup.Element
 if panel = document.ElementByID("mainMasterView-home-pad-KeyButton-KeyNotReadyPanel"); panel == nil {
	err = fmt.Errorf("unable to find #mainMasterView-home-pad-KeyButton-KeyNotReadyPanel")
		return
    }
    group.keyNotReadyPanel = panel.JSValue()
 if panel = document.ElementByID("mainMasterView-home-pad-KeyButton-KeyReadyPanel"); panel == nil {
	err = fmt.Errorf("unable to find #mainMasterView-home-pad-KeyButton-KeyReadyPanel")
		return
    }
    group.keyReadyPanel = panel.JSValue()

	return
}

/*
	Show panel funcs.

	Call these from the controller, presenter and messenger.
*/

// showKeyNotReadyPanel shows the panel you named KeyNotReadyPanel while hiding any other panels in this panel group.
// This panel's id is mainMasterView-home-pad-KeyButton-KeyNotReadyPanel.
// This panel either becomes visible immediately or whenever this group of panels is made visible.  Whenever could be immediately if this panel group is currently visible.
// Param force boolean effects when this panel becomes visible.
//  * if force is true then
//    immediately if the home button pad is not currently displayed;
//    whenever if the home button pad is currently displayed.
//  * if force is false then whenever.
/* Your note for this panel is:
Shown when no codes are selected in references.
Display a message telling the user that no codes are selected.

*/
func (group *panelGroup) showKeyNotReadyPanel(force bool) {
	viewtools.ShowPanelInButtonGroup(group.keyNotReadyPanel, force)
}

// showKeyReadyPanel shows the panel you named KeyReadyPanel while hiding any other panels in this panel group.
// That panel's id is mainMasterView-home-pad-KeyButton-KeyReadyPanel.
// That panel either becomes visible immediately or whenever this group of panels is made visible.  Whenever could be immediately if this panel group is currently visible.
// Param force boolean effects when that panel becomes visible.
//  * if force is true then
//    immediately if the home button pad is not currently displayed;
//    whenever if the home button pad is currently displayed.
//  * if force is false then whenever.
/* Your note for that panel is:

*/
func (group *panelGroup) showKeyReadyPanel(force bool) {
	viewtools.ShowPanelInButtonGroup(group.keyReadyPanel, force)
}
