package keywpmpanel

import (
	"syscall/js"

	"github.com/pkg/errors"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// panelGroup is a group of 1 panel.
// It also has a show panel func for each panel in this panel group.
type panelGroup struct {
	keyWPMPanel js.Value
}

func (group *panelGroup) defineMembers() (err error) {

	defer func() {
		if err != nil {
			err = errors.WithMessage(err, "(group *panelGroup) defineMembers()")
		}
	}()

	if group.keyWPMPanel = notJS.GetElementByID("tabsMasterView_home_pad_KeyButton_KeyReadyPanel_tab_bar-KeyWPMTabPanel-inner-KeyWPMPanel"); group.keyWPMPanel == null {
		err = errors.New("unable to find #tabsMasterView_home_pad_KeyButton_KeyReadyPanel_tab_bar-KeyWPMTabPanel-inner-KeyWPMPanel")
		return
	}

	return
}

/*
	Show panel funcs.

	Call these from the controller, presenter and caller.
*/

// showKeyWPMPanel shows the panel you named KeyWPMPanel while hiding any other panels in this panel group.
// This panel will become visible only when this group of panels becomes visible.
/* Your note for this panel is:
Let the user select the words per miniute for Keying.
*/
func (group *panelGroup) showKeyWPMPanel() {
	tools.ShowPanelInTabGroup(group.keyWPMPanel)
}

