package main

import (
	"github.com/josephbudd/cwt/domain/interfaces/caller"
	"github.com/josephbudd/cwt/domain/types"
	"github.com/josephbudd/cwt/renderer/interfaces/panelHelper"
	"github.com/josephbudd/cwt/renderer/notjs"
	"github.com/josephbudd/cwt/renderer/panels/CopyButton/CopyNotReadyPanel"
	"github.com/josephbudd/cwt/renderer/panels/CopyButton/CopyReadyPanel/PracticeTab/CopyPracticePanel"
	"github.com/josephbudd/cwt/renderer/panels/CopyButton/CopyReadyPanel/TestTab/CopyTestPanel"
	"github.com/josephbudd/cwt/renderer/panels/CopyButton/CopyReadyPanel/WPMTab/CopyWPMPanel"
	"github.com/josephbudd/cwt/renderer/panels/KeyButton/KeyNotReadyPanel"
	"github.com/josephbudd/cwt/renderer/panels/KeyButton/KeyReadyPanel/PracticeTab/KeyPracticePanel"
	"github.com/josephbudd/cwt/renderer/panels/KeyButton/KeyReadyPanel/TestTab/KeyTestPanel"
	"github.com/josephbudd/cwt/renderer/panels/KeyButton/KeyReadyPanel/WPMTab/KeyWPMPanel"
	"github.com/josephbudd/cwt/renderer/panels/ReferenceButton/SelectCodesPanel/LettersTab/LettersPanel"
	"github.com/josephbudd/cwt/renderer/panels/ReferenceButton/SelectCodesPanel/NumbersTab/NumbersPanel"
	"github.com/josephbudd/cwt/renderer/panels/ReferenceButton/SelectCodesPanel/PunctuationTab/PunctuationPanel"
	"github.com/josephbudd/cwt/renderer/panels/ReferenceButton/SelectCodesPanel/SpecialTab/SpecialPanel"
	"github.com/josephbudd/cwt/renderer/viewtools"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

func doPanels(quitCh chan struct{}, tools *viewtools.Tools, callMap map[types.CallID]caller.Renderer, notJS *notjs.NotJS, helper panelHelper.Helper) (err error) {
	// 1. Construct the panel code.
	var copyNotReadyPanel *CopyNotReadyPanel.Panel
	if copyNotReadyPanel, err = CopyNotReadyPanel.NewPanel(quitCh, tools, notJS, callMap, helper); err != nil {
		return
	}
	var copyPracticePanel *CopyPracticePanel.Panel
	if copyPracticePanel, err = CopyPracticePanel.NewPanel(quitCh, tools, notJS, callMap, helper); err != nil {
		return
	}
	var copyTestPanel *CopyTestPanel.Panel
	if copyTestPanel, err = CopyTestPanel.NewPanel(quitCh, tools, notJS, callMap, helper); err != nil {
		return
	}
	var copyWPMPanel *CopyWPMPanel.Panel
	if copyWPMPanel, err = CopyWPMPanel.NewPanel(quitCh, tools, notJS, callMap, helper); err != nil {
		return
	}
	var keyNotReadyPanel *KeyNotReadyPanel.Panel
	if keyNotReadyPanel, err = KeyNotReadyPanel.NewPanel(quitCh, tools, notJS, callMap, helper); err != nil {
		return
	}
	var keyPracticePanel *KeyPracticePanel.Panel
	if keyPracticePanel, err = KeyPracticePanel.NewPanel(quitCh, tools, notJS, callMap, helper); err != nil {
		return
	}
	var keyTestPanel *KeyTestPanel.Panel
	if keyTestPanel, err = KeyTestPanel.NewPanel(quitCh, tools, notJS, callMap, helper); err != nil {
		return
	}
	var keyWPMPanel *KeyWPMPanel.Panel
	if keyWPMPanel, err = KeyWPMPanel.NewPanel(quitCh, tools, notJS, callMap, helper); err != nil {
		return
	}
	var lettersPanel *LettersPanel.Panel
	if lettersPanel, err = LettersPanel.NewPanel(quitCh, tools, notJS, callMap, helper); err != nil {
		return
	}
	var numbersPanel *NumbersPanel.Panel
	if numbersPanel, err = NumbersPanel.NewPanel(quitCh, tools, notJS, callMap, helper); err != nil {
		return
	}
	var punctuationPanel *PunctuationPanel.Panel
	if punctuationPanel, err = PunctuationPanel.NewPanel(quitCh, tools, notJS, callMap, helper); err != nil {
		return
	}
	var specialPanel *SpecialPanel.Panel
	if specialPanel, err = SpecialPanel.NewPanel(quitCh, tools, notJS, callMap, helper); err != nil {
		return
	}

	// 2. Size the app.
	tools.SizeApp()

	// 3. Start each panel's initial calls.
	copyNotReadyPanel.InitialCalls()
	copyPracticePanel.InitialCalls()
	copyTestPanel.InitialCalls()
	copyWPMPanel.InitialCalls()
	keyNotReadyPanel.InitialCalls()
	keyPracticePanel.InitialCalls()
	keyTestPanel.InitialCalls()
	keyWPMPanel.InitialCalls()
	lettersPanel.InitialCalls()
	numbersPanel.InitialCalls()
	punctuationPanel.InitialCalls()
	specialPanel.InitialCalls()

	return
}
